<?php
/**
 * JulioReis_CorreiosFollowup
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  JulioReis
 * @package   JulioReis_CorreiosFollowup
 *
 * @copyright Copyright (c) 2018 Julio Reis (www.rapidets.com.br)
 *
 * @author    Julio Reis <julioreis.si@gmail.com>
 */

namespace JulioReis\CorreiosFollowup\Helper\Tracking;

class Queue
{
    /**
     * @param $statusMsg string
     * @return string
     */
    public function getCorreiosStatus($statusMsg)
    {
        if (strpos($statusMsg, 'Objeto entregue ao destinat') !== false) {
            return \JulioReis\CorreiosFollowup\Model\Tracking\Queue::CORREIOS_STATUS_DELIVERED;
        }
        return \JulioReis\CorreiosFollowup\Model\Tracking\Queue::CORREIOS_STATUS_PROCESSING;
    }
}
