<h1><strong>PS5 ganha nome oficial e tem detalhes de lançamento confirmados pela Sony</strong></h1>
<p>O lançamento do&nbsp;<a href="https://www.techtudo.com.br/tudo-sobre/ps5.html">PS5</a>
    &nbsp;ganhou mais detalhes nesta terça-feira (8), com matéria exclusiva da revista Wired em parceria
    com a&nbsp;<a href="https://www.techtudo.com.br/tudo-sobre/sony.html">Sony</a>. A fabricante
    confirmou o nome PlayStation 5 (ou PS5), seguindo o padrão de títulos estabelecido desde o primeiro
    modelo do videogame. O lançamento do console está confirmado para final de 2020, ainda sem data mais
    específica, mas a previsão é que o videogame chegue ao mercado próximo ao Natal para aproveitar as
    vendas festivas.</p>
<p>A Sony confirmou à Wired a veracidade do kit de desenvolvimento do PS5
    (versão inicial do console) que vazou na
    Internet na última semana. O kit de desenvolvimento é distribuído exclusivamente a estúdios que
    produzem os jogos,
    para que os títulos sejam feitos antes do lançamento do aparelho. A versão vazada do PS5 mostra
    um aparelho em formato “V”, que é o algarismo romano para “cinco”,
    remetendo à edição do PlayStation.</p>
<img src='<?php echo $this->getViewFileUrl('WebJump_Page::images/ps5.png'); ?>' alt="image-icon" width="700"
     height="500">
