<?php
/**
 * JulioReis_CorreiosFollowup
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  JulioReis
 * @package   JulioReis_CorreiosFollowup
 *
 * @copyright Copyright (c) 2018 Julio Reis (www.rapidets.com.br)
 *
 * @author    Julio Reis <julioreis.si@gmail.com>
 */

namespace JulioReis\CorreiosFollowup\Model\Tracking;

use JulioReis\CorreiosFollowup\Model\ResourceModel\Tracking\Queue as ResourceModel;
use Magento\Framework\Model\AbstractModel;

class Queue extends AbstractModel
{
    const CORREIOS_STATUS_PROCESSING = 'P';
    const CORREIOS_STATUS_CANCELED = 'C';
    const CORREIOS_STATUS_DELIVERED = 'D';

    public function _construct()
    {
        $this->_init(ResourceModel::class);
    }
}
